"""Генерация google_sa_embedded.py из секрета или локального credentials.json.

Источники (приоритет):
1. Env GOOGLE_SERVICE_ACCOUNT_JSON (raw JSON или base64) — используется в GitHub Actions.
2. Файл credentials.json рядом (локальная разработка).

Результат: google_sa_embedded.py с GOOGLE_SA_JSON = {...} (автоматически попадает в exe).
Файл НЕ коммитить (см. .gitignore).
"""

import base64
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "google_sa_embedded.py"


def _load_raw() -> str | None:
    raw = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()
    if raw:
        # base64?
        if not raw.startswith("{"):
            try:
                return base64.b64decode(raw).decode("utf-8")
            except Exception as e:
                print(f"WARN: cannot base64-decode secret: {e}", file=sys.stderr)
                return None
        return raw
    # fallback: локальный credentials.json
    for cand in (ROOT / "credentials.json", Path.cwd() / "credentials.json"):
        if cand.is_file():
            try:
                return cand.read_text(encoding="utf-8")
            except Exception as e:
                print(f"WARN: cannot read {cand}: {e}", file=sys.stderr)
                return None
    return None


def main() -> int:
    raw = _load_raw()
    if not raw:
        OUT.write_text("# no embedded key (secret empty, no credentials.json)\nGOOGLE_SA_JSON = None\n", encoding="utf-8")
        print("gen_embedded_sa: no source -> wrote empty stub")
        return 0
    try:
        data = json.loads(raw)
    except Exception as e:
        print(f"ERROR: invalid JSON: {e}", file=sys.stderr)
        return 1
    if not isinstance(data, dict) or data.get("type") != "service_account":
        print("ERROR: JSON is not a service_account key", file=sys.stderr)
        return 1
    OUT.write_text(
        "# auto-generated by tools/gen_embedded_sa.py — DO NOT COMMIT\nGOOGLE_SA_JSON = " + repr(data) + "\n",
        encoding="utf-8",
    )
    print(f"gen_embedded_sa: embedded {data.get('client_email')} -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
