"""Генерация google_oauth_embedded.py из секрета или локального token.json.

Источники (приоритет):
1. Env GOOGLE_OAUTH_TOKEN (raw JSON или base64) — используется в GitHub Actions.
2. Файл token.json рядом (после tools/google_oauth_login.py).

Результат: google_oauth_embedded.py с GOOGLE_OAUTH_JSON = {...} (автоматически попадает в exe).
Файл НЕ коммитить (см. .gitignore).
"""

import base64
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "google_oauth_embedded.py"


def _load_raw() -> str | None:
    raw = os.environ.get("GOOGLE_OAUTH_TOKEN", "").strip()
    if raw:
        if not raw.startswith("{"):
            try:
                return base64.b64decode(raw).decode("utf-8")
            except Exception as e:
                print(f"WARN: cannot base64-decode secret: {e}", file=sys.stderr)
                return None
        return raw
    for cand in (ROOT / "token.json", Path.cwd() / "token.json"):
        if cand.is_file():
            try:
                return cand.read_text(encoding="utf-8")
            except Exception as e:
                print(f"WARN: cannot read {cand}: {e}", file=sys.stderr)
                return None
    return None


def main() -> int:
    raw = _load_raw()
    if not raw:
        OUT.write_text("# no embedded token (secret empty, no token.json)\nGOOGLE_OAUTH_JSON = None\n", encoding="utf-8")
        print("gen_embedded_oauth: no source -> wrote empty stub")
        return 0
    try:
        data = json.loads(raw)
    except Exception as e:
        print(f"ERROR: invalid JSON: {e}", file=sys.stderr)
        return 1
    if not isinstance(data, dict) or not data.get("refresh_token"):
        print("ERROR: JSON has no refresh_token (нужен полный токен из google_oauth_login.py)", file=sys.stderr)
        return 1
    OUT.write_text(
        "# auto-generated by tools/gen_embedded_oauth.py — DO NOT COMMIT\nGOOGLE_OAUTH_JSON = " + repr(data) + "\n",
        encoding="utf-8",
    )
    print(f"gen_embedded_oauth: embedded token -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
